server:
  port: ${SERVER_PORT:18081}

mysql:
  host: ${MYSQL_HOST:localhost}
  port: ${MYSQL_PORT:3306}
  username: ${MYSQL_USER:root}
  password: ${MYSQL_PASSWORD:123456}
  database: ${MYSQL_DATABASE:server-demo}

system:
  feignClient:
    logLevel: ${FEIGNCLIENT_LOGLEVEL:DEBUG}
  sql:
    logLevel: ${SQL_LOGLEVEL:DEBUG}
  log:
    dir: ${LOG_DIR:logs}
  accesslog:
    enabled: ${ACCESSLOG_ENABLED:true}
  flyway:
    enabled: ${FLYWAY_ENABLED:true}

swagger:
  enabled: ${SWAGGER_ENABLED:false}